### ISSUE TITLE
Streamer recorder build error with OpenCV 4.1

### ISSUE THREAD

**Issue by anuppari** [OpenKinect/libfreenect2#1075]
## Overview Description:
Missing macros when compiling with OpenCV 4.1

## Version, Platform, and Hardware Bug Found:

1.dfd4eaf (HEAD -> master, origin/master, origin/HEAD) Add android build script and instructions (#1060)
2. Ubuntu 18.04 (Linux s1039351 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)

## Steps to Reproduce:

1. Compile with OpenCV 4.1

## Actual Results:

Build errors:
```bash
libfreenect2/tools/streamer_recorder/streamer.cpp: In member function ‘void Streamer::initialize()’:
libfreenect2/tools/streamer_recorder/streamer.cpp:39:32: error: ‘CV_IMWRITE_JPEG_QUALITY’ was not declared in this scope
   compression_params.push_back(CV_IMWRITE_JPEG_QUALITY);
                                ^~~~~~~~~~~~~~~~~~~~~~~
libfreenect2/tools/streamer_recorder/recorder.cpp: In member function ‘void Recorder::initialize()’:
libfreenect2/tools/streamer_recorder/recorder.cpp:81:28: error: ‘CV_IMWRITE_JPEG_QUALITY’ was not declared in this scope
   img_comp_param.push_back(CV_IMWRITE_JPEG_QUALITY); //specify the compression technique
```

## Expected Results:
Successful compilation

**Comment by AaboutL** [comment]
Do you fixed this bug?

**Comment by livemixlove** [comment]
You can change it to: cv::IMWRITE_JPEG_QUALITY

**Comment by smokhov** [comment]
Yeah, OpenCV 4 is not supported... Not yet at least. I am not sure how we can elegantly replace `CV_IMWRITE_JPEG_QUALITY` with `cv::IMWRITE_JPEG_QUALITY` for OpenCV4+ and not when using 3-...

**Comment by smokhov** [comment]
Referencing PR #1163 -- hopefully both can be supported somehow.
